/**
 * Inline-style objects for the architecture-explorer sidebar.
 */
import type React from 'react';

export const sidebarStyles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
  },

  // Tabs
  tabBar: {
    display: 'flex',
    borderBottom: '1px solid var(--vscode-widget-border)',
    flexShrink: 0,
  },
  tabBtn: {
    flex: 1,
    padding: '7px 4px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 500,
    color: 'var(--vscode-descriptionForeground)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    borderBottom: '2px solid transparent',
    transition: 'color 0.15s, border-color 0.15s',
  },
  tabBtnActive: {
    color: 'var(--vscode-foreground)',
    borderBottomColor: 'var(--vscode-focusBorder)',
    fontWeight: 700,
  },
  tabBadge: {
    borderRadius: '8px',
    padding: '0 5px',
    fontSize: '9px',
    fontWeight: 700,
    color: '#fff',
    background: 'var(--vscode-badge-background)',
    lineHeight: '14px',
  },

  // Scroll area
  scrollArea: {
    flex: 1,
    overflowY: 'auto',
    padding: '4px 0 8px',
  },
  emptyTab: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px 16px',
    gap: '6px',
    fontSize: '11px',
    color: 'var(--vscode-descriptionForeground)',
    textAlign: 'center',
    opacity: 0.7,
  },

  // System section
  systemSection: {
    borderLeft: '2px solid transparent',
    transition: 'border-color 0.15s',
  },
  systemHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: '7px 10px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: 'var(--vscode-foreground)',
    textAlign: 'left',
  },
  systemHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    minWidth: 0,
    overflow: 'hidden',
  },
  systemHeaderRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    flexShrink: 0,
  },
  chevron: {
    fontSize: '9px',
    color: 'var(--vscode-descriptionForeground)',
    flexShrink: 0,
    width: '10px',
  },
  systemDot: {
    width: '8px',
    height: '8px',
    borderRadius: '2px',
    flexShrink: 0,
  },
  systemName: {
    fontSize: '10px',
    fontWeight: 700,
    letterSpacing: '0.5px',
    color: 'var(--vscode-foreground)',
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
  },
  circBadge: {
    fontSize: '11px',
    color: '#f59e0b',
    fontWeight: 700,
  },
  systemCount: {
    fontSize: '10px',
    color: 'var(--vscode-badge-foreground)',
    background: 'var(--vscode-badge-background)',
    borderRadius: '8px',
    padding: '0 5px',
    minWidth: '18px',
    textAlign: 'center',
    lineHeight: '16px',
  },

  // Explanation
  explainBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    margin: '0 10px 4px 26px',
    padding: '4px 8px',
    background: 'none',
    border: '1px solid var(--vscode-widget-border)',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '10px',
    color: 'var(--vscode-descriptionForeground)',
    width: 'calc(100% - 36px)',
    textAlign: 'left',
  },
  explainBtnActive: {
    background: 'rgba(99,102,241,0.1)',
    borderColor: '#6366f1',
    color: '#a5b4fc',
  },
  explainPanel: {
    margin: '0 10px 6px 26px',
    padding: '10px 12px',
    background: 'rgba(99,102,241,0.06)',
    border: '1px solid rgba(99,102,241,0.18)',
    borderRadius: '6px',
    fontSize: '10px',
    lineHeight: 1.5,
  },
  explainSummary: {
    color: 'var(--vscode-foreground)',
    lineHeight: 1.5,
    fontSize: '10px',
    margin: '0 0 8px',
  },
  explainSection: { marginBottom: '6px' },
  explainSectionTitle: {
    fontSize: '9px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    color: '#6366f1',
    margin: '0 0 3px',
  },
  explainBullet: {
    color: 'var(--vscode-descriptionForeground)',
    paddingLeft: '4px',
    fontSize: '10px',
  },
  explainTags: { display: 'flex', flexWrap: 'wrap', gap: '3px' },
  explainTag: {
    fontSize: '9px',
    padding: '1px 6px',
    borderRadius: '10px',
    background: 'var(--vscode-badge-background)',
    color: 'var(--vscode-badge-foreground)',
  },
  explainWarnings: {
    marginTop: '6px',
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  explainWarning: {
    fontSize: '10px',
    color: '#f59e0b',
    lineHeight: 1.4,
    margin: 0,
  },

  // File list
  fileList: { listStyle: 'none', padding: '0 0 4px', margin: 0 },
  fileItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    width: '100%',
    padding: '4px 10px 4px 30px',
    cursor: 'pointer',
    borderLeftWidth: '2px',
    borderLeftStyle: 'solid',
    borderLeftColor: 'transparent',
    background: 'none',
    border: 'none',
    textAlign: 'left',
    color: 'inherit',
    fontSize: 'inherit',
    fontFamily: 'inherit',
    transition: 'background 0.1s',
  },
  fileItemFocused: {
    background: 'var(--vscode-list-activeSelectionBackground)',
  },
  fileName: {
    fontSize: '11px',
    color: 'var(--vscode-foreground)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    flex: 1,
  },
  fileNameDead: { opacity: 0.4, textDecoration: 'line-through' },
  entryMark: { color: '#f59e0b', fontSize: '7px', marginRight: '3px' },
  fileMetrics: { display: 'flex', alignItems: 'center', gap: '3px', flexShrink: 0 },
  deadMark: { fontSize: '9px', color: '#ef4444', opacity: 0.7 },
  depCount: {
    fontSize: '9px',
    color: 'var(--vscode-descriptionForeground)',
    opacity: 0.6,
    minWidth: '12px',
    textAlign: 'right',
  },
  moreFiles: {
    fontSize: '10px',
    color: 'var(--vscode-descriptionForeground)',
    padding: '4px 30px',
    opacity: 0.6,
  },

  // Violations
  violationGroup: {
    padding: '6px 0 4px',
    borderBottom: '1px solid var(--vscode-widget-border)',
  },
  violationGroupHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 10px 6px',
    fontSize: '10px',
    fontWeight: 700,
    color: 'var(--vscode-foreground)',
    margin: 0,
  },
  violationCard: {
    display: 'flex',
    gap: '8px',
    padding: '5px 10px',
    alignItems: 'flex-start',
  },
  severityDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    flexShrink: 0,
    marginTop: '4px',
  },
  violationContent: { flex: 1, minWidth: 0 },
  violationDesc: {
    fontSize: '10px',
    color: 'var(--vscode-foreground)',
    lineHeight: 1.4,
    margin: '0 0 3px',
  },
  violationFiles: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    flexWrap: 'wrap',
  },
  violationFile: {
    fontSize: '9px',
    color: '#6366f1',
    cursor: 'pointer',
    fontFamily: 'var(--vscode-editor-font-family, monospace)',
    textDecoration: 'underline',
    background: 'none',
    border: 'none',
    padding: 0,
    maxWidth: '90px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  violationArrow: {
    fontSize: '9px',
    color: 'var(--vscode-descriptionForeground)',
  },
  violationMeta: {
    fontSize: '9px',
    color: 'var(--vscode-descriptionForeground)',
    margin: '2px 0 0',
  },

  // Dead zones
  deadZone: {
    padding: '8px 10px',
    borderBottom: '1px solid var(--vscode-widget-border)',
  },
  deadZoneHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginBottom: '4px',
  },
  deadZoneIcon: {
    fontSize: '12px',
    color: '#ef4444',
    opacity: 0.7,
  },
  deadZoneTitle: {
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--vscode-foreground)',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    margin: 0,
  },
  deadZoneCount: {
    fontSize: '10px',
    color: 'var(--vscode-badge-foreground)',
    background: 'var(--vscode-badge-background)',
    borderRadius: '8px',
    padding: '0 5px',
    lineHeight: '16px',
  },
  deadZoneReason: {
    fontSize: '10px',
    color: 'var(--vscode-descriptionForeground)',
    lineHeight: 1.4,
    margin: '0 0 6px',
  },
  deadZoneFiles: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  deadZoneFile: { display: 'flex', alignItems: 'center' },
  deadZoneFileBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    cursor: 'pointer',
    padding: '2px 0',
    opacity: 0.6,
    background: 'none',
    border: 'none',
    color: 'inherit',
    fontSize: 'inherit',
    fontFamily: 'inherit',
    textAlign: 'left',
  },
  deadZoneFileName: {
    fontSize: '10px',
    color: 'var(--vscode-foreground)',
    fontFamily: 'var(--vscode-editor-font-family, monospace)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    textDecoration: 'line-through',
  },
  deadZoneMore: {
    fontSize: '9px',
    color: 'var(--vscode-descriptionForeground)',
    padding: '2px 0',
    opacity: 0.6,
  },
};
