/**
 * Inline-style objects for the graph panel React tree.
 *
 * Keeping styles in their own module keeps the React components focused on
 * structure and behaviour, and lets us share style fragments across components.
 */
import type React from 'react';

export const graphStyles: Record<string, React.CSSProperties> = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    width: '100vw',
    height: '100vh',
    background: 'var(--vscode-editor-background)',
    color: 'var(--vscode-foreground)',
    fontFamily: 'var(--vscode-font-family)',
    overflow: 'hidden',
  },

  // Top bar
  topBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 16px',
    height: '44px',
    borderBottom: '1px solid var(--vscode-editorGroup-border)',
    flexShrink: 0,
    gap: '12px',
  },
  topBarLeft: { display: 'flex', alignItems: 'center', gap: '8px', minWidth: 0 },
  topBarRight: { display: 'flex', alignItems: 'center', gap: '10px', flexShrink: 0 },
  logoText: {
    fontSize: '13px',
    fontWeight: 700,
    letterSpacing: '0.3px',
    color: 'var(--vscode-foreground)',
  },
  divider: {
    width: '1px',
    height: '14px',
    background: 'var(--vscode-editorGroup-border)',
    margin: '0 4px',
  },
  statChip: {
    fontSize: '11px',
    color: 'var(--vscode-descriptionForeground)',
    padding: '2px 8px',
    borderRadius: '10px',
    background: 'var(--vscode-badge-background)',
    whiteSpace: 'nowrap',
  },
  statChipWarn: {
    background: 'var(--vscode-inputValidation-warningBackground, rgba(245,158,11,0.15))',
    color: 'var(--vscode-editorWarning-foreground, #d19a00)',
  },

  // Filter bar
  filterBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 16px',
    borderBottom: '1px solid var(--vscode-editorGroup-border)',
    flexShrink: 0,
    overflowX: 'auto',
    background: 'var(--vscode-editor-background)',
  },
  filterPill: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 10px',
    borderRadius: '14px',
    border: '1px solid var(--vscode-editorGroup-border)',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 500,
    whiteSpace: 'nowrap',
    background: 'transparent',
    color: 'var(--vscode-descriptionForeground)',
    transition: 'all 0.15s ease',
    flexShrink: 0,
  },
  filterPillActive: {
    background:
      'var(--vscode-toolbar-activeBackground, var(--vscode-list-activeSelectionBackground))',
    borderColor: 'var(--vscode-focusBorder)',
    color: 'var(--vscode-foreground)',
  },
  filterPillCount: { fontSize: '10px', opacity: 0.7, fontWeight: 600 },

  // Layout picker
  layoutPicker: {
    display: 'flex',
    gap: '0',
    background: 'var(--vscode-input-background)',
    borderRadius: '6px',
    padding: '2px',
    border: '1px solid var(--vscode-editorGroup-border)',
  },
  layoutBtn: {
    padding: '4px 12px',
    background: 'transparent',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '11px',
    color: 'var(--vscode-descriptionForeground)',
    fontWeight: 500,
    transition: 'all 0.15s ease',
  },
  layoutBtnActive: {
    background: 'var(--vscode-button-background)',
    color: 'var(--vscode-button-foreground)',
  },

  // Graph area
  graphArea: {
    flex: 1,
    overflow: 'hidden',
    position: 'relative',
    background: 'var(--vscode-editor-background)',
  },
  graphCanvas: { width: '100%', height: '100%' },

  // Empty / hint
  emptyOverlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'none',
  },
  emptyText: { fontSize: '13px', color: 'var(--vscode-descriptionForeground)', margin: 0 },
  hint: {
    position: 'absolute',
    top: '16px',
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 14px',
    background: 'var(--vscode-editorWidget-background)',
    border: '1px solid var(--vscode-editorWidget-border, var(--vscode-editorGroup-border))',
    borderRadius: '14px',
    fontSize: '11px',
    color: 'var(--vscode-descriptionForeground)',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    maxWidth: '500px',
  },

  // Toolbar
  toolbar: {
    position: 'absolute',
    right: '16px',
    bottom: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    background: 'var(--vscode-editorWidget-background, var(--vscode-editor-background))',
    border: '1px solid var(--vscode-editorWidget-border, var(--vscode-editorGroup-border))',
    borderRadius: '8px',
    padding: '4px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  toolbarDivider: {
    height: '1px',
    background: 'var(--vscode-editorGroup-border)',
    margin: '2px 4px',
  },
  toolBtn: {
    width: '30px',
    height: '30px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: 'var(--vscode-foreground)',
    borderRadius: '6px',
    transition: 'background 0.15s ease',
  },

  // Legend
  legend: {
    position: 'absolute',
    left: '16px',
    bottom: '16px',
    display: 'flex',
    gap: '12px',
    padding: '6px 12px',
    background: 'var(--vscode-editorWidget-background, var(--vscode-editor-background))',
    border: '1px solid var(--vscode-editorWidget-border, var(--vscode-editorGroup-border))',
    borderRadius: '8px',
    fontSize: '10px',
    color: 'var(--vscode-descriptionForeground)',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  legendItem: { display: 'flex', alignItems: 'center', gap: '6px', whiteSpace: 'nowrap' },

  // Tooltip
  tooltip: {
    position: 'absolute',
    background: 'var(--vscode-editorWidget-background)',
    border: '1px solid var(--vscode-editorWidget-border, var(--vscode-editorGroup-border))',
    borderRadius: '10px',
    padding: '14px',
    width: '240px',
    zIndex: 1000,
    boxShadow: '0 8px 24px rgba(0,0,0,0.2)',
    animation: 'fadeIn 0.18s ease',
  },
  tooltipHead: { display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' },
  tooltipLang: {
    fontSize: '9px',
    fontWeight: 700,
    padding: '2px 6px',
    borderRadius: '4px',
    color: '#fff',
    flexShrink: 0,
    letterSpacing: '0.3px',
  },
  tooltipName: {
    fontSize: '12px',
    fontWeight: 600,
    color: 'var(--vscode-foreground)',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  tooltipClose: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: 'var(--vscode-descriptionForeground)',
    fontSize: '18px',
    lineHeight: 1,
    flexShrink: 0,
    padding: '0 4px',
    borderRadius: '4px',
  },
  tooltipPath: {
    fontSize: '10px',
    color: 'var(--vscode-descriptionForeground)',
    fontFamily: 'var(--vscode-editor-font-family, monospace)',
    margin: '0 0 12px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  tooltipStats: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr 1fr',
    gap: '4px',
    marginBottom: '12px',
    padding: '8px 0',
    borderTop: '1px solid var(--vscode-editorGroup-border)',
    borderBottom: '1px solid var(--vscode-editorGroup-border)',
  },
  tooltipStat: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '2px' },
  tooltipStatVal: {
    fontSize: '15px',
    fontWeight: 700,
    color: 'var(--vscode-foreground)',
    lineHeight: 1,
  },
  tooltipStatKey: {
    fontSize: '9px',
    color: 'var(--vscode-descriptionForeground)',
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
  },
  tooltipBadge: {
    fontSize: '10px',
    color: 'var(--vscode-editorWarning-foreground, #d19a00)',
    margin: '4px 0',
  },
  tooltipOpenBtn: {
    width: '100%',
    padding: '7px',
    background: 'var(--vscode-button-background)',
    color: 'var(--vscode-button-foreground)',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 600,
    marginTop: '4px',
  },

  // Loading
  loading: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100vh',
    gap: '14px',
    background: 'var(--vscode-editor-background)',
  },
  loadingSpinner: {
    width: '28px',
    height: '28px',
    border: '2px solid var(--vscode-editorGroup-border)',
    borderTopColor: 'var(--vscode-focusBorder)',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
  },
  loadingText: { fontSize: '12px', color: 'var(--vscode-descriptionForeground)' },
};
